{% set name = "unicorn-binance-trailing-stop-loss" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - ubtsl=unicorn_binance_trailing_stop_loss.cli:main
  number: 0

channels:
  - lucit
  - conda-forge
  - default

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - lucit::lucit-licensing-python
    - lucit::unicorn-binance-rest-api
    - lucit::unicorn-binance-websocket-api
    - cython
    - requests
  run:
    - python
    - lucit::lucit-licensing-python
    - lucit::unicorn-binance-rest-api
    - lucit::unicorn-binance-websocket-api
    - cython
    - requests

dependencies:
  - anaconda-client
  - conda-build

test:
  imports:
    - unicorn_binance_trailing_stop_loss
  commands:
    - pip check
  requires:
    - pip

about:
  summary: | 
    A Python library with a command line interface for a trailing stop loss and smart entry on the Binance exchange. 
    We also offer a standalone version for Windows and Mac that does not require an installed Python environment.
  description: |

  dev_url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-trailing-stop-loss
  doc_url: https://unicorn-binance-trailing-stop-loss.docs.lucit.tech
  home: https://www.lucit.tech/unicorn-binance-trailing-stop-loss.html
  license: LSOSL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oliver-zehentleitner
